disable amd-update on beta

diff --git a/bin/amd-update b/bin/amd-update
--- a/bin/amd-update
+++ b/bin/amd-update
@@ -7,6 +7,17 @@ echo "Disclaimer: Use at your own risk. If rig not booting after process, you wi
 echo "Hint: 8GB RAM recommended for sucessfull DKMS build."
 echo
 
+
+# Warning
+version=`cat /etc/lsb-release | grep "DISTRIB_RELEASE=" | sed 's/[^.0-9]*//g'`
+if [[ "$version" == *"1.7"* ]]; then
+  echo
+  echo "On Alpha and Beta packages driver updates/downgrades are disabled"
+  echo "because the package shipped with unique customizations that can't be installed with the amd-update tool."
+  echo
+  exit 1
+fi
+
 # Global
 SILENT="no"
 REBOOT="no"
