sunday update

diff --git a/core/dnser b/core/dnser
--- a/core/dnser
+++ b/core/dnser
@@ -14,8 +14,12 @@ fi
 # /etc/hosts
 HCHECK=$(cat /etc/hosts | grep "$SERVERC minerstat.com" | xargs)
 WCHECK=$(cat /etc/hosts | grep "127.0.1.1 $WNAME" | xargs)
+
+CURRENT_DATE=$(date +'%Y-%m-%d')
+CCHECK=$(cat /home/minerstat/cache_date 2>/dev/null)
+
 WNAME=$(cat /media/storage/config.js | grep 'global.worker' | sed 's/global.worker =/"/g' | sed 's/"//g' | sed 's/;//g' | xargs)
-if [ "$HCHECK" != "$SERVERC minerstat.com" ] || [ "$WCHECK" != "127.0.1.1 $WNAME" ]; then
+if [ "$HCHECK" != "$SERVERC minerstat.com" ] || [ "$WCHECK" != "127.0.1.1 $WNAME" ] || [ "$CCHECK" != "$CURRENT_DATE" ]; then
   sudo su -c "echo '$WNAME' > /etc/hostname"
   sudo hostname -F /etc/hostname
   sudo echo "
@@ -36,6 +40,21 @@ $SERVERC api.minerstat.com
 162.159.200.1 ntp.ubuntu.com
 104.24.99.231 labs.minerstat.farm
   " > /etc/hosts
+  # Manage CACHE
+  sudo rm /home/minerstat/mining-pool-whitelist.txt 2>/dev/null
+  wget https://minerstat.com/mining-pool-whitelist.txt -O /home/minerstat/mining-pool-whitelist.txt
+  if [ $? -ne 0 ]; then
+    echo "Cache wget failed. Trying next time"
+  else
+    TEST=$(sudo wc -c /home/minerstat/mining-pool-whitelist.txt | awk '{print $1}')
+    TEST2=$(cat /home/minerstat/mining-pool-whitelist.txt | grep -c "ethermine")
+    if [[ "$TEST" -gt 1000 ]] && [[ "$TEST2" -gt 0 ]]; then
+      echo "Cache valid"
+      sudo cat /home/minerstat/mining-pool-whitelist.txt >> /etc/hosts
+      sudo echo "$CURRENT_DATE" > /home/minerstat/cache_date
+      sync &
+    fi
+  fi
 fi
 
 GET_GATEWAY=$(timeout 5 route -n -e -4 | awk {'print $2'} | grep -vE "0.0.0.0|IP|Gateway" | head -n1 | xargs)
