Update nvidia-update

diff --git a/core/nvidia-update b/core/nvidia-update
--- a/core/nvidia-update
+++ b/core/nvidia-update
@@ -1,132 +1,298 @@
 #!/bin/bash
 
-version=`cat /etc/lsb-release | grep "DISTRIB_RELEASE=" | sed 's/[^.0-9]*//g'`
-if [ "$version" = "1.4" ]; then
-  echo "Updating drivers.."
-  echo "- Mining Stopped!"
-  sudo node /home/minerstat/minerstat-os/stop.js
-  sudo su minerstat -c "screen -X -S minerstat-console quit"
-  echo "stop" > /tmp/stop.pid
-  sudo su -c "sudo screen -X -S minew quit"
-  echo 
-  echo "Waiting (5 SECONDS...)"
-  sleep 5
-  echo
-  echo
-  sudo apt-get update
-  sudo apt --fix-broken install -y
-  sudo apt-get upgrade -y
-  sudo update-initramfs -u
-  #sudo update-grub2
-  sudo dkms install -m nvidia -v $(ls /usr/src | grep nvidia | sed 's/[nvidia][nvidia}]*//' | sed 's/[-][-}]*//')
-  echo "Rebooting.."
-  sleep 5
-  sudo reboot -f
-elif [ "$version" = "1.4.5" ]; then
-  echo "Drivers are up to date"
-  exit 1
-else
-elif [ "$version" = "1.4.9" ]; then
-  echo "Update to: nvidia 450.57"
-  echo "We will make this possible shorty. Try again later."
-  exit 1
-else
-  echo "Currently nvidia-update disabled. Reflash the os to switch between nvidia versions."
-  exit 1
-fi
-
-  exit 2
-if ! grep -q experimental "/etc/lsb-release"; then
-  echo "Driver update not supported on your msos version. Please, reflash to be able to use recent nvidia drivers."
-  exit 1
-fi
-
-echo "- Updating database.. Please, wait"
-sudo apt-get update
 echo
-echo "- Version DB Updated"
-
-ALL_VERSION=$(apt-cache search nvidia | grep -P '^nvidia-[0-9]+\s' | grep "nvidia-" | grep "version" | sed 's/\ .*/ /' | sed 's/[^0-9]*//g')
-LAT_VERSION=$(echo $ALL_VERSION | sed 's/.* //' | sed 's/[^0-9]*//g')
-CUR_VERSION=$(dpkg -l | grep "NVIDIA binary driver" | awk '{ print $2 }' | xargs | sed 's/[^0-9]*//g')
-
-echo "-------- NVIDIA-UPDATER -----------"
+echo "========== Nvidia Driver Update Utility =========="
+echo "It is only recommended to choose 1-2 versions newer or older that you are currently using."
+echo "Disclaimer: Use at your own risk. If rig not booting after process, you will have to reflash."
 echo
 
-echo "- AVAILABLE NVIDIA VERSIONS:" $ALL_VERSION
-echo "- INSTALLED NVIDIA VERSION : $CUR_VERSION"
-echo "- LATEST    NVIDIA VERSION : $LAT_VERSION"
-echo
+# Global vars
+CURRENT_DRIVER=$(timeout 5 nvidia-smi | grep "Driver Version" | xargs | sed 's/[^0-9. ]*//g' | xargs | cut -d ' ' -f 1 | xargs)
+SELECTED_VERSION=""
+VLIST="https://static-ssl.minerstat.farm/drivers/nvidia/nvlist.txt"
+VLIST_TMP="/dev/shm"
+VLIST_FILE="$VLIST_TMP/nvlist.txt"
 
-rebt () {
-  sync
-  sleep 10
-  sudo reboot -f
-}
-
-if [ -z "$1" ]; then
-  echo "Please, provide a version to install."
-  echo "e.g: nvidia-update $LAT_VERSION"
-  echo
-else
-  re='^[0-9]+$'
-  if ! [[ $1 =~ $re ]] ; then
-    echo "ERROR: You only can ENTER numbers" >&2; exit 1
-  else
-    if [[ $ALL_VERSION == *"$1"* ]]; then
-      echo "SELECTED VERSION: $1"
-      # Stop mining
-      echo
-      echo "- Mining Stopped!"
-      sudo node /home/minerstat/minerstat-os/stop.js
-      sudo su minerstat -c "screen -X -S minerstat-console quit"
-      echo "stop" > /tmp/stop.pid
-      sudo su -c "sudo screen -X -S minew quit"
-      echo 
-      echo "Waiting (5 SECONDS...)"
-      sleep 5
-      echo
-      echo
-      if [ "$1" = "$CUR_VERSION" ]; then
-        echo "WARN: This version is already installed.."
-        echo "Checking for updates..."
-        sleep 1
-        sudo apt --fix-broken install -y
-        sudo apt-get install nvidia-$1 -y
-        echo
-        echo "Rebooting in 10 seconds ..."
-        rebt
-      else
-        echo "-----------------------------------"
-        echo "1] Disabling Active kernels"
-        echo "-----------------------------------"
-        sudo su -c "rmmod -f nvidia_uvm; rmmod -f nvidia_drm; rmmod -f nvidia_modeset; rmmod -f nvidia"
-        echo "-----------------------------------"
-        echo "2] Removing Current version"
-        echo "-----------------------------------"
-        sudo apt --fix-broken install -y
-        sudo apt-get purge nvidia-$CUR_VERSION nvidia-opencl-icd-$CUR_VERSION nvidia-settings -y
-        echo "-----------------------------------"
-        echo "3] Installing new version"
-        echo "-----------------------------------"
-        sudo apt-get install nvidia-$1 -y
-        echo "-----------------------------------"
-        echo "4] Activating new kernel modules"
-        echo "-----------------------------------"
-        sudo dkms install -m nvidia -v $(ls /usr/src | grep nvidia | sed 's/[nvidia][nvidia}]*//' | sed 's/[-][-}]*//')
-        echo "-----------------------------------"
-        echo "5] Update initram-fs"
-        echo "-----------------------------------"
-        sudo update-initramfs -u
-        echo "-----------------------------------"
-        echo "6] Reboot"
-        echo "-----------------------------------"
-        rebt
-      fi
-    else
-      echo "ERROR: Invalid version"
-    fi
+# Download driver list
+if [ ! -f "$VLIST_FILE" ]; then
+  wget $VLIST -P $VLIST_TMP
+  if [[ $? -ne 0 ]]; then
+    echo "Download version list file failed.."
+    sudo rm $VLIST_TMP
+    exit 1
   fi
 fi
 
-echo "-----------------------------------"
+# Help
+help () {
+  echo
+  echo "==== Help ===="
+  echo "-h  | --help         : Printing this menu"
+  echo "-l  | --list         : Listing all available driver version to install"
+  echo "-c  | --cuda         : Update cuda libraries"
+  echo "-i  | --install      : Install selected version"
+  echo
+  echo
+  echo "======= Current version: v$CURRENT_DRIVER =========="
+  echo
+  echo "Install Example: nvidia-update --install 455.23.04"
+  echo
+  echo "==================================================="
+  echo
+  exit 9
+}
+
+# List
+list () {
+  # List drivers line by line
+  echo
+  echo "==== Available Versions ====="
+  while read ver; do
+    vers=$(echo $ver | sed -e 's#^NVIDIA-Linux-x86_64-##;' | cut -f1 -d"r" | sed 's/.$//')
+    echo $vers
+  done < $VLIST_FILE
+  echo
+  echo "======= Current version: v$CURRENT_DRIVER =========="
+  echo
+  echo "Update to latest: nvidia-update --install $vers"
+  echo
+  echo "==================================================="
+  echo
+}
+
+# check if EMPTY
+if [[ -z "$1" ]]; then
+  list
+  exit 1
+fi
+
+# List
+install () {
+  # List drivers line by line
+  echo
+  EXISTS="0"
+  while read ver; do
+    VT=$(echo $ver | sed -e 's#^NVIDIA-Linux-x86_64-##;' | cut -f1 -d"r" | sed 's/.$//')
+    if [[ "$VT" = "$SELECTED_VERSION" ]]; then
+      EXISTS="1"
+    fi
+  done < $VLIST_FILE
+  # Check for validity
+  if [[ "$EXISTS" = "1" ]]; then
+    echo
+    echo "================="
+    echo "Valid version provided.. Attempting to download and install Nvidia $SELECTED_VERSION .."
+    echo "================="
+    # Stop And Maintenance mode
+    echo
+    echo "================="
+    echo "Stopping miner/agent and entering into maintenance mode.."
+    echo "================="
+    echo
+    sudo /home/minerstat/minerstat-os/core/stop >/dev/null 2>&1
+    # Unload Nvidia
+    sudo bash /home/minerstat/minerstat-os/bin/nvunload >/dev/null 2>&1
+    sudo init 3
+    # Remove ALL Nvidia
+    sudo killall screen >/dev/null 2>&1
+    #screen -list
+    #sudo screen -list
+    sudo killall X sudo killall Xorg sudo killall Xorg >/dev/null 2>&1
+    # For vanilla uninstall
+    echo
+    echo "================="
+    echo "Removing older versions.. Will take few moments"
+    echo "================="
+    echo
+    sudo apt-get purge -y nvidia*
+    sudo apt-get purge -y nvidia-driver*
+    sudo /usr/bin/nvidia-uninstall --accept-license --no-questions --ui=none
+    # Download
+    FILE="NVIDIA-Linux-x86_64-$SELECTED_VERSION.run"
+    if [ ! -f "/tmp/$FILE" ]; then
+      wget "https://static-ssl.minerstat.farm/drivers/nvidia/$FILE" -P /tmp
+      if [[ $? -ne 0 ]]; then
+        echo "Download driver installer failed.."
+        sudo rm /tmp/$FILE
+        exit 1
+      fi
+    fi
+    # Permissions
+    sudo chmod 777 /tmp/$FILE >/dev/null 2>&1
+    # Install
+    sudo /tmp/$FILE --accept-license --no-questions --ui=none --dkms --no-cc-version-check
+    # Initramfs
+    sudo update-initramfs -u
+    # Sync
+    sync
+    # Install CUDA
+    cuda
+    # Make a safety recovery
+    echo
+    echo "================="
+    echo "Install finished, now making a recovery ..."
+    echo "================="
+    echo
+    sudo su -c "cd /home/minerstat; sudo rm /home/minerstat/recovery.sh; wget https://labs.minerstat.farm/repo/minerstat-os/-/raw/master/core/recovery.sh; sudo chmod 777 /home/minerstat/recovery.sh;"
+    sudo bash /home/minerstat/recovery.sh
+    sudo /home/minerstat/minerstat-os/core/stop >/dev/null 2>&1
+    echo
+    # Check XSERVER
+    SNUM=$(sudo su minerstat -c "screen -list | grep -c display2")
+    if [ "$SNUM" != "1" ]; then
+      sudo su -c "timeout 10 sudo screen -X -S display quit" >/dev/null 2>&1
+      timeout 10 screen -X -S display quit >/dev/null 2>&1
+      timeout 10 screen -X -S display2 quit >/dev/null 2>&1
+      sudo timeout 10 killall X >/dev/null 2>&1
+      sudo timeout 10 killall Xorg >/dev/null 2>&1
+      sudo timeout 5 kill -9 $(sudo pidof Xorg) >/dev/null 2>&1
+      sudo timeout 5 rm /tmp/.X0-lock >/dev/null 2>&1
+      sudo timeout 10 nvidia-xconfig -a --allow-empty-initial-configuration --cool-bits=31 --use-display-device="DFP-0" --connected-monitor="DFP-0"
+      sudo sed -i s/"DPMS"/"NODPMS"/ /etc/X11/xorg.conf >/dev/null 2>&1
+      sudo su minerstat -c "screen -A -m -d -S display2 sudo X :0" >/dev/null 2>&1
+      sleep 20
+    fi
+    # Sync
+    sync
+    # Test NVIDIA-SMI
+    echo
+    TEST=$(sudo /usr/bin/nvidia-smi | grep "Driver")
+    if [[ "$TEST" == *"CUDA"* ]]; then
+      echo
+      echo "================="
+      echo "Driver successfully installed. You can see NVIDIA-SMI Output below."
+      echo "================="
+      echo
+      sudo /usr/bin/nvidia-smi
+    else
+      echo
+      echo "================="
+      echo "Something went wrong, during installing. NVIDIA-SMI not reporting actual driver version."
+      echo "Try again to run installer, or select different version to install."
+      echo "If nothing works, reflash your USB/SSD with an image from minerstat.com"
+      echo "================="
+      echo
+    fi
+    echo
+  else
+    echo
+    echo "================="
+    echo "Invalid driver version number provided. Check available versions with:"
+    echo "nvidia-update --list"
+    echo "================="
+    echo
+    exit 2
+  fi
+  echo
+}
+
+# Download and install cuda .so files
+cuda () {
+  echo
+  echo "================="
+  echo "Installing cuda libraries.."
+  echo "================="
+  if [ ! -f "/tmp/cudalib.zip" ]; then
+    wget "https://static-ssl.minerstat.farm/drivers/nvidia/cudalib.zip" -P /tmp
+    if [[ $? -ne 0 ]]; then
+      echo "Download cuda library failed.."
+      sudo rm /tmp/cudalib.zip
+      exit 1
+    fi
+  fi
+  # unzip
+  sudo unzip -o /tmp/cudalib.zip -d /tmp/cudalib
+  # copy to gnu
+  sudo cp -fva /tmp/cudalib/* /lib/x86_64-linux-gnu
+  # sync
+  sync
+  # sync CUDA
+  if [[ -z "$SELECTED_VERSION" ]]; then
+    SELECTED_VERSION=$CURRENT_DRIVER
+  fi
+  SELECTED_VERSION_CUT=$(echo $SELECTED_VERSION | cut -f1 -d".")
+  echo
+  echo "Installed driver major version number: $SELECTED_VERSION_CUT"
+  if [[ "$SELECTED_VERSION_CUT" -ge 455 ]]; then
+    CUDA="11.0" # Update this later to CUDA v11.1
+  elif [[ "$SELECTED_VERSION_CUT" -ge 450 ]]; then
+    CUDA="11.0"
+  elif [[ "$SELECTED_VERSION_CUT" -ge 440 ]]; then
+    CUDA="10.2"
+  elif [[ "$SELECTED_VERSION_CUT" -ge 418 ]]; then
+    CUDA="10.1"
+  elif [[ "$SELECTED_VERSION_CUT" -ge 410 ]]; then
+    CUDA="10.0"
+  elif [[ "$SELECTED_VERSION_CUT" -ge 396 ]]; then
+    CUDA="9.2"
+  elif [[ "$SELECTED_VERSION_CUT" -lt 396 ]]; then
+    CUDA="9.0"
+  elif [[ "$SELECTED_VERSION_CUT" -lt 320 ]]; then
+    CUDA="8.0"
+  fi
+  echo
+  echo "CUDA v$CUDA will be used as default solver.."
+  echo
+  # Used by some miner for default reference in /lib/x86_64-linux-gnu
+  # libcudart.so, libnvrtc.so, libnvrtc-builtins.so
+  for cudalib in libcudart.so libnvrtc.so libnvrtc-builtins.so; do
+    COPY="/lib/x86_64-linux-gnu/$cudalib.$CUDA"
+    if [ -f "$COPY" ]; then
+      TARGET="/lib/x86_64-linux-gnu/$cudalib"
+      sudo rm $TARGET
+      sudo ln -s $COPY $TARGET
+      REAL=$(realpath /lib/x86_64-linux-gnu/$cudalib)
+      echo "Success: $TARGET is now linked to $COPY"
+      echo "Verify: $REAL"
+    fi
+  done
+  # sync
+  sync
+  echo
+}
+
+# Arg parser
+PARAMS=""
+while (( "$#" )); do
+  case "$1" in
+    -i|--install)
+      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
+        SELECTED_VERSION=$2
+        install
+        shift 2
+      else
+        echo
+        echo "================="
+        echo "Error: Please, select a version to install" >&2
+        echo "================="
+        echo
+        exit 1
+      fi
+      ;;
+    -h|--help)
+      help
+      shift
+      ;;
+    -l|--list)
+      list
+      shift
+      ;;
+    -c|--cuda)
+      cuda
+      shift
+      ;;
+    -*|--*=) # unsupported flags
+      echo "================="
+      echo "Error: Unsupported flag $1" >&2
+      echo "================="
+      exit 1
+      ;;
+    *) # preserve positional arguments
+      PARAMS="$PARAMS $1"
+      shift
+      ;;
+  esac
+done
+# set positional arguments in their proper place
+eval set -- "$PARAMS"
+echo
